local inventory = require("test.std.inventory")
local mixtures = require("test.std.mixtures")
local conversions = require("test.std.conversions")

describe("inventory", function()
  describe("plate test", function()
    it("should build correct addresses and chemicals", function()
      inventory.new_plate("test_plate", "cryoking_300ul")
      inventory.new_tube("m9", 0, mixtures.common_reagents["M9"]:volume(50*conversions.ul))
      inventory.new_tube("neb_buffer_1.1", 1, mixtures.common_reagents["NEBuffer_r1.1_u"]:volume(50*conversions.ul))
      assert(plate.tubes[2].address, 1)
      assert(plate.tubes[1].sample.mixture.chemicals[1].chemical.inchi, "InChI=1S/H2O/h1H2")
    end)
  end)
end)
